# Generated by Django 3.2.7 on 2021-10-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0005_auto_20210929_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
